version: '3.8'

services:
  eureka-server:
    image: eureka-server:latest
    container_name: eureka-server
    build:
      context: ./eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  user-service:
    image: user-service:latest
    container_name: user-service
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - db

  task-service:
    image: task-service:latest
    container_name: task-service
    build:
      context: ./task-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - db

  tag-service:
    image: tag-service:latest
    container_name: tag-service
    build:
      context: ./tag-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - db

  db:
    image: mysql:latest
    container_name: todo-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 2626
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
