server:
  port: 8081

spring:
  application:
    name: user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo_msa_user
    username: root
    password: 2626
    hikari:
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  session:
    store-type: jdbc          # Spring Session JDBC 사용
    jdbc:
      initialize-schema: always  # 스키마 자동 생성
      table-name: spring_session
    cookie:
      name: SESSIONID
      http-only: true         # JavaScript에서 쿠키 접근 불가
      secure: false           # HTTPS 사용 시 true
    timeout:
      session: 30m            # 세션 유효 시간 (30분)


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
